name: Build frontend app and deploy

defaults:
  run:
    working-directory: "frontend/"

on:
  workflow_dispatch:
  push:
    branches:
    - feature/frontend

jobs:
  TestingBuild:
    name: Test and Build
    runs-on: self-hosted

    steps:
    - name: Install and Test
      run: |
        apt-get update && apt-get -y install npm
        npm install -g @angular/cli
        ng test

    - name: Build an Image
      run: |
        docker build -t frontend-app:latest .
