name: Build frontend app and deploy

defaults:
  run:
    working-directory: "frontend/"

on:
  workflow_dispatch:
  push:
    branches:
    - feature/frontend

jobs:
  TestingBuild:
    name: Test and Build
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Set up nodejs 14
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Getting Dependencies
      run: |
        cd app/
        npm install

    - name: Install and Test
      run: |
        npm install -g @angular/cli
        ng test

    - name: Build an Image
      run: |
        docker build -t frontend-app:latest .
