name: Build frontend app and deploy

defaults:
  run:
    working-directory: "frontend/"

on:
  workflow_dispatch:
  push:
    branches:
    - feature/frontend

jobs:
  TestingBuild:
    name: Test and Build
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Install and Test
      run: |
        apt-get update && apt-get -y install npm
        npm install -g @angular/cli
        ng test

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: jafferveronezi.io
        username: ${{ github.actor }}
        password: ${{ secrets.MY_TOKEN }}
    
    - name: Build and push image
      run: |
        docker build -t jafferveronezi.io/frontend-app:1.0 .
        docker push jafferveronezi.io/frontend-app:1.0
